/**
 * Shared setup for the browser tests.
 *
 * Each test gets a fresh jsdom window loaded with real rendered markup and
 * the real script under test. Nothing here reimplements the plugin: the
 * fixtures come from the PHP renderer and the scripts are the files that
 * ship, so a broken selector or a mis-set data attribute fails the test.
 *
 * @package WPCMB
 */

'use strict';

const fs = require( 'node:fs' );
const path = require( 'node:path' );
const { JSDOM } = require( 'jsdom' );

const PLUGIN = path.resolve( __dirname, '..', '..' );

/**
 * Read a fixture generated by build-fixtures.php.
 *
 * @param {string} name Fixture name.
 * @return {string} The markup.
 */
function fixture( name ) {
	return fs.readFileSync( path.join( __dirname, 'fixtures', `${ name }.html` ), 'utf8' );
}

/**
 * Build a window with fixture markup and one or more plugin scripts loaded.
 *
 * @param {Object}   options          Setup options.
 * @param {string}   [options.html]   Fixture markup for the body.
 * @param {string[]} [options.scripts] Script filenames under assets/js.
 * @param {Object}   [options.globals] Globals to define before the scripts run.
 * @param {Function} [options.fetch]   Stub for window.fetch.
 * @return {Object} The jsdom window, plus helpers.
 */
function setup( options = {} ) {
	const dom = new JSDOM( `<!doctype html><html><body>${ options.html || '' }</body></html>`, {
		runScripts: 'outside-only',
		pretendToBeVisual: true,
		url: 'http://localhost/',
	} );

	const { window } = dom;

	// Globals the scripts expect from WordPress, supplied before they run so
	// that anything read at load time sees them.
	Object.assign( window, options.globals || {} );

	if ( options.fetch ) {
		window.fetch = options.fetch;
	}

	( options.scripts || [] ).forEach( ( name ) => {
		const source = fs.readFileSync( path.join( PLUGIN, 'assets', 'js', name ), 'utf8' );
		window.eval( source );
	} );

	// The scripts bind their entry point to DOMContentLoaded, which jsdom has
	// already fired by the time the source is evaluated.
	window.document.dispatchEvent( new window.Event( 'DOMContentLoaded' ) );

	return {
		window,
		document: window.document,

		/**
		 * Query one element.
		 *
		 * @param {string} selector CSS selector.
		 * @return {Element|null} The element.
		 */
		$: ( selector ) => window.document.querySelector( selector ),

		/**
		 * Query every matching element.
		 *
		 * @param {string} selector CSS selector.
		 * @return {Element[]} The elements.
		 */
		$$: ( selector ) => Array.from( window.document.querySelectorAll( selector ) ),

		/**
		 * Click an element the way a person would, so delegated handlers see it.
		 *
		 * @param {Element} element The element.
		 */
		click: ( element ) => {
			element.dispatchEvent( new window.MouseEvent( 'click', { bubbles: true, cancelable: true } ) );
		},

		/**
		 * Set a control's value and announce it.
		 *
		 * @param {Element} element The control.
		 * @param {string}  value   The value.
		 */
		fill: ( element, value ) => {
			element.value = value;
			element.dispatchEvent( new window.Event( 'input', { bubbles: true } ) );
			element.dispatchEvent( new window.Event( 'change', { bubbles: true } ) );
		},

		/**
		 * Check or uncheck a box and announce it.
		 *
		 * @param {Element} element The checkbox.
		 * @param {boolean} checked Whether it should be checked.
		 */
		check: ( element, checked ) => {
			element.checked = checked;
			element.dispatchEvent( new window.Event( 'change', { bubbles: true } ) );
		},

		/**
		 * Wait for pending promise callbacks to run.
		 *
		 * @return {Promise} Resolves after the microtask queue drains.
		 */
		settle: () => new Promise( ( resolve ) => setTimeout( resolve, 0 ) ),
	};
}

/**
 * A jQuery stand-in providing only what the scripts actually call.
 *
 * The scripts use jQuery for one thing: jQuery UI's sortable, which is a
 * pointer-driven plugin that cannot be meaningfully exercised in jsdom. This
 * records that sortable was set up — so a test can prove the script asked for
 * drag support — without pretending to test dragging itself.
 *
 * @return {Function} The stub.
 */
function jqueryStub() {
	const calls = [];

	const $ = ( target ) => ( {
		sortable: ( config ) => {
			calls.push( { target, config } );
			return $;
		},
	} );

	$.fn = { sortable: true };
	$.calls = calls;

	return $;
}

module.exports = { fixture, setup, jqueryStub, PLUGIN };
